# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 24, 12, 39, 49, 301308)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 24, 12, 39, 57, 736262)),
            preserve_default=False,
        ),
    ]
